### PR TITLE
Add missing fallbackToSettings argument on native iOS side

### PR DESCRIPTION
**Pull request by slawekkrol**
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/523)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
@slawekkrol Thanks for the PR, the code changes themselves looks like it will work. Can you note the iOS version and Flutter version you have tested this on?

**Comment by slawekkrol** [comment]
> @slawekkrol Thanks for the PR, the code changes themselves looks like it will work. Can you note the iOS version and Flutter version you have tested this on?

Flutter 2.5.3 • channel stable
Tools • Dart 2.14.4
iOS 15.2

But IMO this really doesn't matter because this change is only native ObjC code in one place, so this code must works on every version iOS and flutter

**Review by jkasten2 — APPROVED** [review]
Thanks for providing those details.

**Review by tanaynigam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/523#-:-Mx145tL61YiyROn4TbW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nan-li)

**Pull request merged**
